version: "3.2"

services:
  starknet:
    image: gchr.io/keep-starknet-strange/madara:v0.7.0
    ports:
      - 9615:9615
      - 30333:30333
      - 5050:5050
    entrypoint: [/bin/bash, -c]
    command: >
      "/madara-bin setup --from-remote --chain=dev && /madara-bin --rpc-external --rpc-methods=unsafe --rpc-cors=all --rpc-port 5050 --chain=dev --base-path=/home/madara --alice --force-authoring"
    volumes:
      - madara:/home/madara
    networks:
      - internal
    restart: on-failure

  kakarot-deployer:
    extends:
      file: docker-compose.yaml
      service: kakarot-deployer
    env_file:
      - ./docker/env/kakarot-deployer.madara.env

  deployments-parser:
    extends:
      file: docker-compose.yaml
      service: deployments-parser

  kakarot-rpc:
    extends:
      file: docker-compose.yaml
      service: kakarot-rpc

  apibara-dna:
    extends:
      file: docker-compose.yaml
      service: apibara-dna

  mongo:
    extends:
      file: docker-compose.yaml
      service: mongo

  indexer:
    extends:
      file: docker-compose.yaml
      service: indexer

networks:
  internal:

volumes:
  deployments:
  apibara:
  mongo_data:
  indexer_code:
  madara:
